version: '2'

services:

  mysql-db-dev:
    image: mysql:5.7.16
    container_name: mysql-db-dev
    hostname: mysql-db-dev
    ports:
      - "3306:3306"
    volumes:
      - ./migrations/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_DATABASE=my_schema

  oracle-db-dev:
    image: container-registry.oracle.com/database/enterprise:12.1.0.2
    container_name: oracle-db-dev
    hostname: oracle-db-dev
    shm_size: 4224m
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - DB_PASSWD=Password1234

  oracle-db-preload-dev:
    image: container-registry.oracle.com/database/instantclient:12.2.0.1
    command: /bin/bash -c "sqlplus system/Password1234@oracle-db-dev:1521/ORCL.localdomain < /sql/system/001_create_my_owner_up.sql && sqlplus my_owner/my_owner@oracle-db-dev:1521/ORCL.localdomain < /sql/ssc_owner/001_ips_up.sql"
    container_name: oracle-db-preload-dev
    hostname: oracle-db-preload-dev
    volumes:
      - ./migrations/oracle:/sql
    depends_on:
      - oracle-db-dev

  oracle-golang:
    build:
      context: .
      dockerfile: docker/golang_oracle_client/Dockerfile
    command: /bin/bash -c "go build -o /go/bin/oracle github.com/veqryn/personal/src/oracle && /go/bin/oracle"
    container_name: oracle-golang
    hostname: oracle-golang
    volumes:
      - .:/go/src/github.com/veqryn/personal
    depends_on:
      - oracle-db-dev
