
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

DROP USER my_owner;
CREATE USER my_owner IDENTIFIED BY my_owner;

GRANT
  CREATE SESSION,
  ALTER SESSION,
  CREATE DATABASE LINK,
  CREATE MATERIALIZED VIEW,
  CREATE PROCEDURE,
  CREATE PUBLIC SYNONYM,
  CREATE ROLE,
  CREATE SEQUENCE,
  CREATE SYNONYM,
  CREATE TABLE,
  CREATE TRIGGER,
  CREATE TYPE,
  CREATE VIEW,
  UNLIMITED TABLESPACE
TO my_owner;
